apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "revenge.fullname" . }}
  labels:
    {{- include "revenge.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "revenge.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "revenge.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.revenge.server.port }}
          env:
            - name: REVENGE_SERVER_PORT
              value: {{ .Values.revenge.server.port | quote }}
            - name: REVENGE_DATABASE_HOST
              value: {{ include "revenge.databaseHost" . | quote }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
