{{- if and .Values.media.persistence.enabled (not .Values.media.persistence.existingClaim) (not .Values.media.persistence.nfs.server) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "revenge.fullname" . }}-media
  labels:
    {{- include "revenge.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.media.persistence.accessMode }}
  {{- if .Values.media.persistence.storageClass }}
  storageClassName: {{ .Values.media.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.media.persistence.size }}
{{- end }}
---
{{- if and .Values.postgresql.enabled .Values.postgresql.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "revenge.fullname" . }}-pgdata
  labels:
    {{- include "revenge.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size }}
{{- end }}
---
{{- if and .Values.typesense.enabled .Values.typesense.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "revenge.fullname" . }}-tsdata
  labels:
    {{- include "revenge.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.typesense.persistence.size }}
{{- end }}
