apiVersion: v1
kind: Service
metadata:
  name: {{ include "revenge.fullname" . }}
  labels:
    {{- include "revenge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      name: http
  selector:
    {{- include "revenge.selectorLabels" . | nindent 4 }}
