apiVersion: v2
name: revenge
description: A modern, self-hosted media server
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/lusoris/revenge
sources:
  - https://github.com/lusoris/revenge
maintainers:
  - name: lusoris
keywords:
  - media-server
  - self-hosted
  - streaming
